Extension { #name : 'RowanSample9V4TestCase' }

{ #category : 'tests' }
RowanSample9V4TestCase >> testCiv1 [  self assert: RowanSample9V4Class1 civ1 = nil
]

{ #category : 'tests' }
RowanSample9V4TestCase >> testCiv2 [  self assert: RowanSample9V4Class1 civ2 = nil
]

{ #category : 'tests' }
RowanSample9V4TestCase >> testCv1 [  self assert: RowanSample9V4Class1 new cv1 = nil
]

{ #category : 'tests' }
RowanSample9V4TestCase >> testCv2 [  self assert: RowanSample9V4Class1 new cv2 = nil
]

{ #category : 'tests' }
RowanSample9V4TestCase >> testIv1 [  self assert: RowanSample9V4Class1 new iv1 = nil
]

{ #category : 'tests' }
RowanSample9V4TestCase >> testIv2 [  self assert: RowanSample9V4Class1 new iv2 = nil
]
