"
I am an example class
"
Class {
	#name : 'RowanSample9V4Class1',
	#superclass : 'Object',
	#instVars : [
		'iv2'
	],
	#classVars : [
		'Cv2'
	],
	#classInstVars : [
		'civ2'
	],
	#category : 'RowanSample9V4-C06'
}

{ #category : 'accessing' }
RowanSample9V4Class1 class >> civ2 [ ^ civ2
]

{ #category : 'accessing' }
RowanSample9V4Class1 >> cv2 [ ^ Cv2
]

{ #category : 'accessing' }
RowanSample9V4Class1 >> iv2 [ ^ iv2
]
