Extension { #name : 'RowanSample9V4Class1' }

{ #category : '*rowansample9v4-extensions' }
RowanSample9V4Class1 class >> bar [ ^'bar'
]

{ #category : '*rowansample9v4-extensions' }
RowanSample9V4Class1 class >> bar4 [ ^4
]

{ #category : '*rowansample9v4-extensions' }
RowanSample9V4Class1 class >> bar5 [ ^5
]

{ #category : '*rowansample9v4-extensions' }
RowanSample9V4Class1 >> foo4 [ ^4
]

{ #category : '*rowansample9v4-extensions' }
RowanSample9V4Class1 >> foo5 [ ^5
]

{ #category : '*rowansample9v4-extensions' }
RowanSample9V4Class1 >> foo6 [ ^6
]
