"
I am an example class
"
Class {
	#name : 'RowanSample9V4Class1',
	#superclass : 'Object',
	#instVars : [
		'ivar1'
	],
	#category : 'RowanSample9V4-Core'
}

{ #category : 'accessing' }
RowanSample9V4Class1 class >> _123abc [      
	^self
]

{ #category : 'accessing' }
RowanSample9V4Class1 class >> _abc123 [ ^self
]

{ #category : 'accessing' }
RowanSample9V4Class1 class >> _ABC123 [ ^self
]

{ #category : 'accessing' }
RowanSample9V4Class1 class >> a_bc123 [ ^self
]

{ #category : 'accessing' }
RowanSample9V4Class1 >> _123Abc [ 
	^self
]

{ #category : 'accessing' }
RowanSample9V4Class1 >> A_bc123 [      ^self
]

{ #category : 'accessing' }
RowanSample9V4Class1 >> foo [ ^1
]
