Trait {
	#name : 'RowanSample9V4Trait1',
	#instVars : [
		'iv1',
		'iv2'
	],
	#classInstVars : [
		'civ1',
		'civ2'
	],
	#classVars : [
		'Cv1',
		'Cv2'
	],
	#category : 'RowanSample9V4-Tr02'
}

{ #category : 'accessing' }
RowanSample9V4Trait1 class >> civ1_t [ ^ civ1
]

{ #category : 'accessing' }
RowanSample9V4Trait1 class >> civ2_t [ ^ civ2
]

{ #category : 'accessing' }
RowanSample9V4Trait1 >> cv1_t [ ^ Cv1
]

{ #category : 'accessing' }
RowanSample9V4Trait1 >> cv2_t [ ^ Cv2
]

{ #category : 'accessing' }
RowanSample9V4Trait1 >> iv1_t [ ^ iv1
]

{ #category : 'accessing' }
RowanSample9V4Trait1 >> iv2_t [ ^ iv2
]
