"
I am an example class
"
Class {
	#name : 'RowanSample9V4Class1',
	#superclass : 'Object',
	#instVars : [
		'iv1',
		'iv2'
	],
	#classVars : [
		'Cv1',
		'Cv2'
	],
	#classInstVars : [
		'civ1',
		'civ2'
	],
	#traits : 'RowanSample9V4Trait1',
	#classTraits : 'RowanSample9V4Trait1 classTrait',
	#category : 'RowanSample9V4-C02'
}

{ #category : 'accessing' }
RowanSample9V4Class1 class >> civ1 [ ^ civ1
]

{ #category : 'accessing' }
RowanSample9V4Class1 class >> civ2 [ ^ civ2
]

{ #category : 'accessing' }
RowanSample9V4Class1 >> cv1 [ ^ Cv1
]

{ #category : 'accessing' }
RowanSample9V4Class1 >> cv2 [ ^ Cv2
]

{ #category : 'accessing' }
RowanSample9V4Class1 >> iv1 [ ^ iv1
]

{ #category : 'accessing' }
RowanSample9V4Class1 >> iv2 [ ^ iv2
]
